### ISSUE TITLE
initialize': Function not implemented - Failed to initialize inotify (Errno::ENOSYS)

### ISSUE THREAD

**Issue by anderskitson** [tombeynon/akash-deploy#4]
When I try and run the image i get the following output and it just exits. 

I am running a M1 Mac with docker for that Arc, so maybe it's related to that.

```

=> Booting Puma

=> Rails 5.2.4.5 application starting in development

=> Run `rails server -h` for more startup options

Exiting

Traceback (most recent call last):

71: from bin/rails:4:in `<main>'

70: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

69: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

68: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

67: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

66: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

65: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands.rb:18:in `<top (required)>'

64: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/command.rb:46:in `invoke'

63: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/command/base.rb:69:in `perform'

62: from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'

61: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'

60: from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'

59: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:142:in `perform'

58: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:142:in `tap'

57: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:147:in `block in perform'

56: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:51:in `start'

55: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'

54: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'

53: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/commands/server/server_command.rb:27:in `app'

52: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'

51: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'

50: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'

49: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'

48: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'

47: from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'

46: from config.ru:3:in `block in <main>'

45: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'

44: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'

43: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'

42: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'

41: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'

40: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'

39: from /app/config/environment.rb:5:in `<top (required)>'

38: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/application.rb:361:in `initialize!'

37: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/initializable.rb:60:in `run_initializers'

36: from /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'

35: from /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'

34: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'

33: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'

32: from /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'

31: from /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'

30: from /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'

29: from /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

28: from /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'

27: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/initializable.rb:61:in `block in run_initializers'

26: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/initializable.rb:32:in `run'

25: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/initializable.rb:32:in `instance_exec'

24: from /usr/local/bundle/gems/railties-5.2.4.5/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'

23: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'

22: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:51:in `each'

21: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'

20: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'

19: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'

18: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'

17: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/i18n_railtie.rb:19:in `block in <class:Railtie>'

16: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/i18n_railtie.rb:61:in `initialize_i18n'

15: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/i18n_railtie.rb:61:in `new'

14: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/evented_file_update_checker.rb:67:in `initialize'

13: from /usr/local/bundle/gems/activesupport-5.2.4.5/lib/active_support/evented_file_update_checker.rb:96:in `boot!'

12: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'

11: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'

10: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'

9: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'

8: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'

7: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'

6: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:63:in `start'

5: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `configure'

4: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:40:in `each'

3: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/base.rb:45:in `block in configure'

2: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:31:in `_configure'

1: from /usr/local/bundle/gems/listen-3.1.5/lib/listen/adapter/linux.rb:31:in `new'

/usr/local/bundle/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:69:in `initialize': Function not implemented - Failed to initialize inotify (Errno::ENOSYS)
```

**Comment by tombeynon** [comment]
Related: https://github.com/docker/for-mac/issues/5321

I need to find some time to look at this - we are using an arm64 compatible base image (ruby:2.5). I might need a bit of help debugging too @anderskitson  as I don't have an M1 device currently.
