### ISSUE TITLE
ExitError in DeploymentsController#edit

### ISSUE THREAD

**Issue by MbBrainz** [tombeynon/akash-deploy#7]
Came from Deployments and clicked edit. This is the page i then got back:
[errorpage-Action Controller_ Exception caught.pdf](https://github.com/tombeynon/akash-deploy/files/6836396/errorpage-Action.Controller_.Exception.caught.pdf)

This is the docker log: 

```
Started GET "/deployments/1832854/edit" for 172.17.0.1 at 2021-07-18 14:05:26 +0000

Cannot render console from 172.17.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

Processing by DeploymentsController#edit as HTML

Parameters: {"id"=>"1832854"}

[fd38b3cf] Running akash keys show deploy -a --home /root/akash --keyring-backend file


[fd38b3cf] akash1ygsrc9t4l6squvq25hlr9k26j7hp9f99u8h6ly


[fd38b3cf] Finished in 0.224 seconds with exit status 0 (successful)


[f0f19a72] Running curl -s https://raw.githubusercontent.com/ovrclk/net/master/mainnet/rpc-nodes.txt | sort -R | head -1


[f0f19a72] http://rpc.mainnet.akash.dual.systems:80


[f0f19a72] Finished in 0.112 seconds with exit status 0 (successful)


[0fe05bf6] Running akash query bank balances akash1ygsrc9t4l6squvq25hlr9k26j7hp9f99u8h6ly -o json --home /root/akash --node http://rpc.mainnet.akash.dual.systems:80


[0fe05bf6] {"balances":[{"denom":"uakt","amount":"4975000"}],"pagination":{"next_key":null,"total":"0"}}

[0fe05bf6] Finished in 0.828 seconds with exit status 0 (successful)


[9f0a8c86] Running akash query deployment list --owner akash1ygsrc9t4l6squvq25hlr9k26j7hp9f99u8h6ly --dseq 1832854 -o json --home /root/akash --node http://rpc.mainnet.akash.dual.systems:80


[9f0a8c86] Error: error unmarshalling: invalid character '<' looking for beginning of value


[9f0a8c86] Finished in 30.291 seconds with exit status 1 (failed)

Completed 500 Internal Server Error in 31504ms




TTY::Command::ExitError (Running `akash query deployment list --owner akash1ygsrc9t4l6squvq25hlr9k26j7hp9f99u8h6ly --dseq 1832854 -o json --home /root/akash --node http://rpc.mainnet.akash.dual.systems:80` failed with

exit status: 1

stdout: Nothing written

stderr: Error: error unmarshalling: invalid character '<' looking for beginning of value

):


lib/akash/cli.rb:58:in `run'

lib/akash/cli.rb:47:in `cmd'

lib/akash/cli.rb:42:in `cmd_json'

lib/akash/deployments.rb:42:in `get_deployments'

lib/akash/deployments.rb:11:in `find'

app/controllers/deployments_controller.rb:24:in `edit'
```

**Comment by tombeynon** [comment]
This does occur sometimes, especially if you try to open multiple tabs of the deploy UI at the same time. I will leave this issue open as it can at least be handled more gracefully, but you can get around it by simply refreshing the page.
